---
trigger: none

pool:
  vmImage: windows-latest
  
variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: BuildBlaiseFileUploadAlien
    displayName: Build Blaise File Upload Alien
    jobs:
      - job: BuildApp
        displayName: Build and Publish
        pool: 
          vmImage: 'windows-latest'
        steps:
          - checkout: self

          - task: UseDotNet@2
            displayName: Install .NET 10
            inputs:
              packageType: sdk
              version: 10.x

          - task: DotNetCoreCLI@2
            displayName: 'Restore and Build Solution'
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration $(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: Run unit tests
            inputs:
              command: test
              projects: |
                **/*[Tt]est*.csproj
                !**/*Behaviour.csproj
              arguments: --configuration $(buildConfiguration) --no-build

          - task: DotNetCoreCLI@2
            displayName: 'Dotnet Publish (win-x64)'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '**/BlaiseFileUploadAlien.csproj'
              arguments: '-c $(buildConfiguration) -r win-x64 --self-contained false -o $(Build.ArtifactStagingDirectory)/BlaiseFileUploadAlien'
              zipAfterPublish: false

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: BlaiseFileUploadAlien'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/BlaiseFileUploadAlien'
              ArtifactName: 'BlaiseFileUploadAlien'
              publishLocation: 'Container'
